### ISSUE TITLE
how to restart the tor/server  in docker to make a second onion link 

### ISSUE THREAD

**Issue by nardcart** [d-a-s-h-o/tor-php-hosting#2]
how to restart the tor/server  in docker to make a second onion link

i could not do that

**Comment by d-a-s-h-o** [comment]
Check /etc/tor/torrc make and make sure that the second site is uncommented
Check /etc/apache2/ports.conf make sure that apache is listening to the correct ports
Check /etc/apache2/sites-available/ make sure that file 2.conf exists
Check /etc/apache2/sites-available/2.conf make sure that the file is correctly made
Check /var/www/html/.files/2/ exists and add site content to directory
Run as root in shell `a2ensite 2.conf` to enable site
Run as root in shell `service apache2 reload` to reload apache2 server

✔️ You're done!

**Comment by Doomlol** [comment]
ok bro thanks

**Comment by Doomlol** [comment]
bro what happened to the chatterbox.tk and host.onionz.tk why
 "Temporarily Terminated"

can i help with some thing
will it come back

**Comment by d-a-s-h-o** [comment]
Everything has been moved over to the [Onionz](https://onionz.dev/) dashboard and unified into one project I guess.
